-- ============================
-- MEMBERSHIP LEVELS
-- ============================
CREATE TABLE membership_levels (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(100) UNIQUE NOT NULL,
  tier INT NOT NULL,
  price_ore INT NOT NULL,
  max_saved_recipes INT NOT NULL,
  description TEXT
);

INSERT INTO membership_levels (name, slug, tier, price_ore, max_saved_recipes, description) VALUES
('Basic', 'basic', 1, 0, 0, 'Grundnivå med begränsad åtkomst'),
('Premium', 'premium', 2, 4990, 10, 'Full åtkomst till recept och sparade favoriter'),
('Premium Plus', 'premium-plus', 3, 7990, NULL, 'Maximal åtkomst och exklusivt innehåll');

-- ============================
-- USERS
-- ============================
CREATE TABLE users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(50) DEFAULT 'user',
  membership_level_id INT REFERENCES membership_levels(id),
  created_at TIMESTAMP DEFAULT NOW()
);

-- ============================
-- CATEGORIES 
-- ============================
CREATE TABLE categories (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) UNIQUE NOT NULL
);

INSERT INTO categories (name) VALUES
('Frukost'),
('Lunch'),
('Middag');

-- ============================
-- RECIPES
-- ============================
CREATE TABLE recipes (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) UNIQUE NOT NULL,
  required_level_id INT REFERENCES membership_levels(id),
  category_id INT REFERENCES categories(id),
  intro TEXT,
  instructions TEXT[] NOT NULL,
  image_url VARCHAR(255),
  cook_time_min INT,
  is_published BOOLEAN DEFAULT FALSE,
  created_by INT REFERENCES users(id),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- ============================
-- RECIPE INGREDIENTS
-- ============================
CREATE TABLE recipe_ingredients (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id INT REFERENCES recipes(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  amount decimal,
  unit VARCHAR(50),
  sort_order INT DEFAULT 0
);

-- ============================
-- SAVED RECIPES (MANY-TO-MANY)
-- ============================
CREATE TABLE saved_recipes (
  user_id INT REFERENCES users(id) ON DELETE CASCADE,
  recipe_id INT REFERENCES recipes(id) ON DELETE CASCADE,
  saved_at TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY (user_id, recipe_id)
);

-- ============================
-- RECEIPTS (BETALNINGAR)
-- ============================
CREATE TABLE receipts (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT REFERENCES users(id),
  membership_level_id INT REFERENCES membership_levels(id),
  order_reference VARCHAR(255) NOT NULL,
  amount_ore INT NOT NULL,
  level_name_snapshot VARCHAR(255) NOT NULL,
  status VARCHAR(50) NOT NULL,
  paid_at TIMESTAMP DEFAULT NOW()
);










